CREATE TABLE ARTICLES (
    ARTICLE_ID INT(255) NOT NULL AUTO_INCREMENT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TITLE VARCHAR(300),
    INTRO VARCHAR(1000),
    CONTENT TEXT,
    HERO_IMG INT(255),
    EDIT BOOLEAN,
    AUTHOR INT(255),
    HIDDEN BOOLEAN DEFAULT TRUE,
    PRIMARY KEY(ARTICLE_ID),
    CONSTRAINT FOREIGN KEY (HERO_IMG) REFERENCES IMAGES(IMAGE_ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT FOREIGN KEY (AUTHOR) REFERENCES USER(ID)
        ON UPDATE CASCADE,
        ON DELETE SET NULL
);

