CREATE TABLE COMMENTS(
    COMMENT_ID INT(255) NOT NULL AUTO_INCREMENT,
    ARTICLE_ID INT(255) NOT NULL,
    AUTHOR VARCHAR(40),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APPROVED BOOLEAN NOT NULL DEFAULT FALSE,
    TRASHED BOOLEAN NOT NULL DEFAULT FALSE,
    CONTENT TEXT,
    PRIMARY KEY(COMMENT_ID),
    CONSTRAINT FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
)