CREATE TABLE IMAGES_IN_GALLERY(
    IIG_ID INT(255) NOT NULL AUTO_INCREMENT,
    ARTICLE_ID INT(255),
    IMAGE_ID INT(255),
    PRIMARY KEY(IIG_ID),
    CONSTRAINT ARTICLE_FK FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLES(ARTICLE_ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
    CONSTRAINT IMAGE_FK FOREIGN KEY (IMAGE_ID) REFERENCES IMAGES(IMAGE_ID)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);