SELECT IMAGES.IMAGE_NAME, IMAGES.CREATED, IMAGES.IMAGE_ID, PZ.COUNT_G, PG.COUNT_H
FROM IMAGES
LEFT JOIN
    (SELECT IMAGE_ID, COUNT(*) AS COUNT_G
    FROM IMAGES_IN_GALLERY
    GROUP BY IMAGE_ID) AS PZ
    ON IMAGES.IMAGE_ID = PZ.IMAGE_ID
LEFT JOIN
    (SELECT HERO_IMG, COUNT(*) AS COUNT_H
    FROM ARTICLES
    GROUP BY HERO_IMG) AS PG
    ON IMAGES.IMAGE_ID = PG.HERO_IMG
ORDER BY IMAGES.CREATED DESC;